schema_version = 1
template_version = "1.20.1-template-1.0.0"

[mod]
mod_id = "example"
mod_name = "example"
version = "0.0.1"
version_suffix = ""
group = "com.mihono.pickaid"
authors = ["example"]
license = "MIT"
description = "Pexample.\nexample line."
credits = "None"
issue_tracker_url = "https://github.com/org/repo/issues"

[features]
jei = false
curios = false
geckolib = false
player_animator = false
kubejs = true
mixin_extras = true

[overrides]

[publish]
maven_url = "https://maven.mihono.cn/repository/pickaid1201/"
curseforge_project = 0
modrinth_project = ""
release_type = "alpha"

[naming]
archive_name = "example"
jar_format = "{archive_name}-{mc_version}-{version}"
