modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
${file_metadata_lines}

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''${mod_description}'''
${mod_metadata_lines}

[[mixins]]
config="${mod_id}.mixins.json"

${access_transformer_block}

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
${mod_relation_blocks}
